# Generated by Django 5.2.6 on 2025-09-14 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adm_temporarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='data_incio',
            new_name='data_inicio',
        ),
    ]
