# Generated by Django 5.2.6 on 2025-09-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_adm_temporarios', '0002_rename_data_incio_contratos_data_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contratos',
            old_name='avtivo',
            new_name='ativo',
        ),
    ]
